package com.telmarket.intelimarket.entity;
// Generated Dec 18, 2018 7:06:11 PM by Hibernate Tools 4.3.1



/**
 * DeliveryCost generated by hbm2java
 */
public class DeliveryCost  implements java.io.Serializable {


     private Integer deliveryId;
     private String zoneName;
     private double deliveryCost;

    public DeliveryCost() {
    }

    public DeliveryCost(String zoneName, double deliveryCost) {
       this.zoneName = zoneName;
       this.deliveryCost = deliveryCost;
    }
   
    public Integer getDeliveryId() {
        return this.deliveryId;
    }
    
    public void setDeliveryId(Integer deliveryId) {
        this.deliveryId = deliveryId;
    }
    public String getZoneName() {
        return this.zoneName;
    }
    
    public void setZoneName(String zoneName) {
        this.zoneName = zoneName;
    }
    public double getDeliveryCost() {
        return this.deliveryCost;
    }
    
    public void setDeliveryCost(double deliveryCost) {
        this.deliveryCost = deliveryCost;
    }




}


