package com.telmarket.intelimarket.entity;
// Generated Dec 18, 2018 7:06:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Cacheable;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Product generated by hbm2java
 */
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class Product  implements java.io.Serializable {

     private Integer proId;
     private SubCategory subCategory;
     private String proName;
     private double proPrice;
     private int proQty;
     private String proDesc;
     private String proPic;
     private Set productOrders = new HashSet(0);
     private Set productOrderDetailses = new HashSet(0);

    public Product() {
    }

	
    public Product(SubCategory subCategory, String proName, double proPrice, int proQty, String proDesc, String proPic) {
        this.subCategory = subCategory;
        this.proName = proName;
        this.proPrice = proPrice;
        this.proQty = proQty;
        this.proDesc = proDesc;
        this.proPic = proPic;
    }
    public Product(SubCategory subCategory, String proName, double proPrice, int proQty, String proDesc, String proPic, Set productOrders, Set productOrderDetailses) {
       this.subCategory = subCategory;
       this.proName = proName;
       this.proPrice = proPrice;
       this.proQty = proQty;
       this.proDesc = proDesc;
       this.proPic = proPic;
       this.productOrders = productOrders;
       this.productOrderDetailses = productOrderDetailses;
    }
   
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public SubCategory getSubCategory() {
        return this.subCategory;
    }
    
    public void setSubCategory(SubCategory subCategory) {
        this.subCategory = subCategory;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public double getProPrice() {
        return this.proPrice;
    }
    
    public void setProPrice(double proPrice) {
        this.proPrice = proPrice;
    }
    public int getProQty() {
        return this.proQty;
    }
    
    public void setProQty(int proQty) {
        this.proQty = proQty;
    }
    public String getProDesc() {
        return this.proDesc;
    }
    
    public void setProDesc(String proDesc) {
        this.proDesc = proDesc;
    }
    public String getProPic() {
        return this.proPic;
    }
    
    public void setProPic(String proPic) {
        this.proPic = proPic;
    }
    public Set getProductOrders() {
        return this.productOrders;
    }
    
    public void setProductOrders(Set productOrders) {
        this.productOrders = productOrders;
    }
    public Set getProductOrderDetailses() {
        return this.productOrderDetailses;
    }
    
    public void setProductOrderDetailses(Set productOrderDetailses) {
        this.productOrderDetailses = productOrderDetailses;
    }




}


