package com.telmarket.intelimarket.entity;
// Generated Jul 8, 2018 3:59:47 PM by Hibernate Tools 4.3.1



/**
 * ProductOrderDetails generated by hbm2java
 */
public class ProductOrderDetails  implements java.io.Serializable {


     private Integer orderDetId;
     private Product product;
     private ProductOrder productOrder;
     private int proQty;

    public ProductOrderDetails() {
    }

    public ProductOrderDetails(Product product, ProductOrder productOrder, int proQty) {
       this.product = product;
       this.productOrder = productOrder;
       this.proQty = proQty;
    }
   
    public Integer getOrderDetId() {
        return this.orderDetId;
    }
    
    public void setOrderDetId(Integer orderDetId) {
        this.orderDetId = orderDetId;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public ProductOrder getProductOrder() {
        return this.productOrder;
    }
    
    public void setProductOrder(ProductOrder productOrder) {
        this.productOrder = productOrder;
    }
    public int getProQty() {
        return this.proQty;
    }
    
    public void setProQty(int proQty) {
        this.proQty = proQty;
    }




}


